version: 2

updates:
- package-ecosystem: gomod
  directory: /
  schedule: {interval: daily}

- package-ecosystem: elm
  directory: /web/elm
  schedule: {interval: daily}

- package-ecosystem: npm
  directory: /
  schedule: {interval: daily}

- package-ecosystem: npm
  directory: /web/wats
  schedule: {interval: daily}

- package-ecosystem: github-actions
  directory: /
  schedule: {interval: daily}
