platform: linux

image_resource:
  type: mock
  source: {mirror_self: true}

params:
  INTERFACE: eth0
  EXPECTED_MTU:

run:
  path: sh
  args:
  - -c
  - |
    set -ex

    actual_mtu="$(cat /sys/class/net/$INTERFACE/mtu)"
    test "$actual_mtu" = "$EXPECTED_MTU"
